package wasi:random@0.3.0-rc-2026-01-06;

@since(version = 0.3.0-rc-2026-01-06)
world imports {
    @since(version = 0.3.0-rc-2026-01-06)
    import random;

    @since(version = 0.3.0-rc-2026-01-06)
    import insecure;

    @since(version = 0.3.0-rc-2026-01-06)
    import insecure-seed;
}
