package wasi:filesystem@0.3.0-rc-2026-01-06;

@since(version = 0.3.0-rc-2026-01-06)
interface preopens {
    @since(version = 0.3.0-rc-2026-01-06)
    use types.{descriptor};

    /// Return the set of preopened directories, and their paths.
    @since(version = 0.3.0-rc-2026-01-06)
    get-directories: func() -> list<tuple<descriptor, string>>;
}
