@since(version = 0.2.0)
interface stdin {
  use wasi:io/streams@0.2.0.{input-stream};

  @since(version = 0.2.0)
  get-stdin: func() -> input-stream;
}

@since(version = 0.2.0)
interface stdout {
  use wasi:io/streams@0.2.0.{output-stream};

  @since(version = 0.2.0)
  get-stdout: func() -> output-stream;
}

@since(version = 0.2.0)
interface stderr {
  use wasi:io/streams@0.2.0.{output-stream};

  @since(version = 0.2.0)
  get-stderr: func() -> output-stream;
}
