name: 'Install WIT Tools'
description: 'Installs wit-deps and wasm-tools for WIT validation'

inputs:
  wit-deps-version:
    description: 'Version of wit-deps to install'
    required: false
    default: '0.5.0'
  wasm-tools-version:
    description: 'Version of wasm-tools to install'
    required: false
    default: '1.242.0'

runs:
  using: 'composite'
  steps:
    - name: Setup wasm-tools
      uses: bytecodealliance/actions/wasm-tools/setup@v1
      with:
        version: ${{ inputs.wasm-tools-version }}

    - name: Cache wit-deps
      id: cache-wit-deps
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ~/.local/bin/wit-deps
        key: wit-deps-${{ inputs.wit-deps-version }}

    - name: Install wit-deps
      if: steps.cache-wit-deps.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p ~/.local/bin
        curl -Lo ~/.local/bin/wit-deps \
          "https://github.com/bytecodealliance/wit-deps/releases/download/v${{ inputs.wit-deps-version }}/wit-deps-x86_64-unknown-linux-musl"
        chmod +x ~/.local/bin/wit-deps

    - name: Add wit-deps to PATH
      shell: bash
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
