/// This interface defines an HTTP client. It may be imported by components that
/// wish to send HTTP Requests or it may be composed with a `handler` to process
/// requests without any use of a network. In addition, it may be exported by
/// components to wrap another `client` as with "client interceptors".
interface client {
  use types.{request, response, error-code};

  /// This function may be used to either send an outgoing request over the
  /// network or to forward it to another component.
  send: async func(
    request: request,
  ) -> result<response, error-code>;
}
