/// This interface defines a handler of HTTP Requests. It may be exported by
/// components which can respond to HTTP Requests. In addition, it may be
/// imported by components to wrap another `handler` as with "middleware".
interface handler {
  use types.{request, response, error-code};

  /// This function may be called with either an incoming request read from the
  /// network or a request synthesized or forwarded by another component.
  handle: async func(
    request: request,
  ) -> result<response, error-code>;
}