@since(version = 0.3.0)
interface types {
    /// Error codes.
    ///
    /// In theory, every API can return any error code.
    /// In practice, API's typically only return the errors documented per API
    /// combined with a couple of errors that are always possible:
    /// - `unknown`
    /// - `access-denied`
    /// - `not-supported`
    /// - `out-of-memory`
    ///
    /// See each individual API for what the POSIX equivalents are. They sometimes differ per API.
    @since(version = 0.3.0)
    enum error-code {
        /// Unknown error
        unknown,

        /// Access denied.
        ///
        /// POSIX equivalent: EACCES, EPERM
        access-denied,

        /// The operation is not supported.
        ///
        /// POSIX equivalent: EOPNOTSUPP
        not-supported,

        /// One of the arguments is invalid.
        ///
        /// POSIX equivalent: EINVAL
        invalid-argument,

        /// Not enough memory to complete the operation.
        ///
        /// POSIX equivalent: ENOMEM, ENOBUFS, EAI_MEMORY
        out-of-memory,

        /// The operation timed out before it could finish completely.
        timeout,

        /// The operation is not valid in the socket's current state.
        invalid-state,

        /// A bind operation failed because the provided address is not an address that the `network` can bind to.
        address-not-bindable,

        /// A bind operation failed because the provided address is already in use or because there are no ephemeral ports available.
        address-in-use,

        /// The remote address is not reachable
        remote-unreachable,


        /// The TCP connection was forcefully rejected
        connection-refused,

        /// The TCP connection was reset.
        connection-reset,

        /// A TCP connection was aborted.
        connection-aborted,


        /// The size of a datagram sent to a UDP socket exceeded the maximum
        /// supported size.
        datagram-too-large,
    }

    /// Lookup error codes.
    @since(version = 0.3.0)
    enum lookup-error {
        /// Unknown error
        unknown,

        /// Access denied.
        ///
        /// POSIX equivalent: EACCES, EPERM
        access-denied,

        /// `name` is a syntactically invalid domain name or IP address.
        ///
        /// POSIX equivalent: EINVAL
        invalid-argument,

        /// Name does not exist or has no suitable associated IP addresses.
        ///
        /// POSIX equivalent: EAI_NONAME, EAI_NODATA, EAI_ADDRFAMILY
        name-unresolvable,

        /// A temporary failure in name resolution occurred.
        ///
        /// POSIX equivalent: EAI_AGAIN
        temporary-resolver-failure,

        /// A permanent failure in name resolution occurred.
        ///
        /// POSIX equivalent: EAI_FAIL
        permanent-resolver-failure,
    }

    @since(version = 0.3.0)
    enum ip-address-family {
        /// Similar to `AF_INET` in POSIX.
        ipv4,

        /// Similar to `AF_INET6` in POSIX.
        ipv6,
    }

    @since(version = 0.3.0)
    type ipv4-address = tuple<u8, u8, u8, u8>;
    @since(version = 0.3.0)
    type ipv6-address = tuple<u16, u16, u16, u16, u16, u16, u16, u16>;

    @since(version = 0.3.0)
    variant ip-address {
        ipv4(ipv4-address),
        ipv6(ipv6-address),
    }

    @since(version = 0.3.0)
    record ipv4-socket-address {
        /// sin_port
        port: u16,
        /// sin_addr
        address: ipv4-address,
    }

    @since(version = 0.3.0)
    record ipv6-socket-address {
        /// sin6_port
        port: u16,
        /// sin6_flowinfo
        flow-info: u32,
        /// sin6_addr
        address: ipv6-address,
        /// sin6_scope_id
        scope-id: u32,
    }

    @since(version = 0.3.0)
    variant ip-socket-address {
        ipv4(ipv4-socket-address),
        ipv6(ipv6-socket-address),
    }
}
