package wasi:sockets@0.3.0-draft;

@since(version = 0.3.0)
world imports {
    @since(version = 0.3.0)
    import network;
    @since(version = 0.3.0)
    import udp;
    @since(version = 0.3.0)
    import udp-create-socket;
    @since(version = 0.3.0)
    import tcp;
    @since(version = 0.3.0)
    import tcp-create-socket;
    @since(version = 0.3.0)
    import ip-name-lookup;
}
