package wasi:sockets@0.3.0-rc-2026-02-05;

@since(version = 0.3.0-rc-2026-02-05)
world imports {
    @since(version = 0.3.0-rc-2026-02-05)
    import types;
    @since(version = 0.3.0-rc-2026-02-05)
    import ip-name-lookup;
}
