
/// This interface provides a value-export of the default network handle..
default interface default-network {
	use pkg.network.{network}

	/// Get a handle to the default network.
	default-network: func() -> network

}