package wasi:clocks@0.3.0-rc-2026-02-05;

@since(version = 0.3.0-rc-2026-02-05)
world imports {
    @since(version = 0.3.0-rc-2026-02-05)
    import monotonic-clock;
    @since(version = 0.3.0-rc-2026-02-05)
    import system-clock;
    @unstable(feature = clocks-timezone)
    import timezone;
}
