package wasi:clocks@0.3.0-rc-2025-08-14;

@since(version = 0.3.0-rc-2025-08-14)
world imports {
    @since(version = 0.3.0-rc-2025-08-14)
    import monotonic-clock;
    @since(version = 0.3.0-rc-2025-08-14)
    import wall-clock;
    @unstable(feature = clocks-timezone)
    import timezone;
}
