package wasi:clocks@0.3.0-rc-2026-01-06;

@since(version = 0.3.0-rc-2026-01-06)
world imports {
    @since(version = 0.3.0-rc-2026-01-06)
    import monotonic-clock;
    @since(version = 0.3.0-rc-2026-01-06)
    import system-clock;
    @unstable(feature = clocks-timezone)
    import timezone;
}
