package wasi:cli@0.3.0-rc-2026-03-15;

@since(version = 0.3.0-rc-2026-03-15)
world command {
  @since(version = 0.3.0-rc-2026-03-15)
  include imports;

  @since(version = 0.3.0-rc-2026-03-15)
  export run;
}
