package wasi:cli@0.3.0-rc-2026-02-05;

@since(version = 0.3.0-rc-2026-02-05)
world command {
  @since(version = 0.3.0-rc-2026-02-05)
  include imports;

  @since(version = 0.3.0-rc-2026-02-05)
  export run;
}
