package wasi:cli@0.3.0-rc-2026-02-05;

@since(version = 0.3.0-rc-2026-02-05)
world imports {
  @since(version = 0.3.0-rc-2026-02-05)
  include wasi:clocks/imports@0.3.0-rc-2026-02-05;
  @since(version = 0.3.0-rc-2026-02-05)
  include wasi:filesystem/imports@0.3.0-rc-2026-02-05;
  @since(version = 0.3.0-rc-2026-02-05)
  include wasi:sockets/imports@0.3.0-rc-2026-02-05;
  @since(version = 0.3.0-rc-2026-02-05)
  include wasi:random/imports@0.3.0-rc-2026-02-05;

  @since(version = 0.3.0-rc-2026-02-05)
  import environment;
  @since(version = 0.3.0-rc-2026-02-05)
  import exit;
  @since(version = 0.3.0-rc-2026-02-05)
  import stdin;
  @since(version = 0.3.0-rc-2026-02-05)
  import stdout;
  @since(version = 0.3.0-rc-2026-02-05)
  import stderr;
  @since(version = 0.3.0-rc-2026-02-05)
  import terminal-input;
  @since(version = 0.3.0-rc-2026-02-05)
  import terminal-output;
  @since(version = 0.3.0-rc-2026-02-05)
  import terminal-stdin;
  @since(version = 0.3.0-rc-2026-02-05)
  import terminal-stdout;
  @since(version = 0.3.0-rc-2026-02-05)
  import terminal-stderr;
}
