name: WASI release

on:
  workflow_dispatch:
    inputs:
      wasi_version:
        description: 'WASI version (without the v)'
        required: true
        default: '0.2.5'

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for PRs and full history
      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@v1.12.5
      - name: Install wit-bindgen
        shell: bash
        run: cargo binstall -y wit-bindgen-cli wit-deps-cli


      - name: Run WASI deps script
        run: ./scripts/wasi-deps.sh "${{ github.event.inputs.wasi_version }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Release WASI v${{ github.event.inputs.wasi_version }}"
          branch: release-v${{ github.event.inputs.wasi_version }}
          title: "Release WASI v${{ github.event.inputs.wasi_version }}"
          body: |
            Release v${{ inputs.wasi_version }}.
          base: main
          delete-branch: true

